//! `konpu scaffold` — 法則テストのスケルトン生成。
//!
//! 指定パスのアノテーション付き宣言を走査し、各宣言の `required_laws_for` を
//! law ごとにスケルトン化する。生成テストには law アノテーションも付けるので
//! そのまま `konpu check --test-results` で発見・検証できる。
//!
//! - Rust: `<stem>_law_tests.rs`（`#[konpu::law(..)]` + `#[test]`）
//! - Swift: `<stem>LawTests.swift`（`// konpu: law(..)` + XCTest メソッド）

use std::path::{Path, PathBuf};

use crate::analyze::check::required_laws_for;
use crate::analyze::parser::{self, Language};
use crate::analyze::template::ResolvedConfig;
use crate::domain::konpu::Law;

#[derive(Debug, Clone)]
pub struct ScaffoldedFile {
    pub path: PathBuf,
    pub contents: String,
    pub decl_count: usize,
    pub test_count: usize,
}

/// パスごとに 1 つの scaffolded file を返す（言語別）。
pub fn scaffold_path(path: &Path, _config: &ResolvedConfig) -> Vec<ScaffoldedFile> {
    let mut out = Vec::new();
    for (file, lang) in parser::collect_source_files(path) {
        if let Some(s) = scaffold_one(&file, lang) {
            out.push(s);
        }
    }
    out
}

/// 宣言 1 件から (型名, law) の並びを作る。
fn law_pairs(file: &Path, lang: Language) -> Option<(Vec<(String, Law)>, usize)> {
    let source = std::fs::read_to_string(file).ok()?;
    let tree = parser::parse_with(&source, lang)?;
    let root = tree.root_node();
    let decls = match lang {
        Language::Rust => crate::analyze::extract::extract_declarations(root, &source, file),
        Language::Swift => crate::analyze::extract_swift::extract_declarations(root, &source, file),
        Language::Kotlin => crate::analyze::extract_kotlin::extract_declarations(root, &source, file),
        Language::Ts => crate::analyze::extract_ts::extract_declarations(root, &source, file),
    };
    if decls.is_empty() {
        return None;
    }
    let mut pairs = Vec::new();
    for decl in &decls {
        for law in required_laws_for(&decl.target_structure) {
            pairs.push((decl.type_name.clone(), law));
        }
    }
    (!pairs.is_empty()).then_some((pairs, decls.len()))
}

fn scaffold_one(file: &Path, lang: Language) -> Option<ScaffoldedFile> {
    let (pairs, decl_count) = law_pairs(file, lang)?;
    let test_count = pairs.len();
    let (contents, path) = match lang {
        Language::Rust => (render_rust(file, &pairs), out_path(file, "_law_tests.rs")),
        Language::Swift => (render_swift(file, &pairs), out_path(file, "LawTests.swift")),
        Language::Kotlin => (render_kotlin(file, &pairs), out_path(file, "LawTests.kt")),
        Language::Ts => (render_ts(file, &pairs), out_path(file, ".laws.test.ts")),
    };
    Some(ScaffoldedFile { path, contents, decl_count, test_count })
}

fn render_rust(file: &Path, pairs: &[(String, Law)]) -> String {
    let mut body = format!(
        "//! Generated by `konpu scaffold` from `{}`.\n//! Fill the bodies to encode each law, then run your test suite.\n\n",
        file.display()
    );
    for (ty, law) in pairs {
        let kind = law_kind_str(law);
        let fn_name = format!("test_{ty}_{kind}");
        body.push_str(&format!(
            "#[konpu::law({kind})]\n#[test]\nfn {fn_name}() {{ unimplemented!(\"konpu scaffold: {fn_name}\") }}\n\n"
        ));
    }
    body
}

fn render_swift(file: &Path, pairs: &[(String, Law)]) -> String {
    let stem = stem_of(file);
    let mut body = format!(
        "// Generated by `konpu scaffold` from `{}`.\n// Fill the bodies to encode each law, then run `swift test`.\nimport XCTest\n\nfinal class {stem}LawTests: XCTestCase {{\n",
        file.display()
    );
    for (ty, law) in pairs {
        let kind = law_kind_str(law);
        let fn_name = format!("test_{ty}_{kind}");
        body.push_str(&format!(
            "    // konpu: law({kind})\n    func {fn_name}() {{ /* TODO: konpu scaffold — encode {kind} for {ty} */ }}\n\n"
        ));
    }
    body.push_str("}\n");
    body
}

fn render_kotlin(file: &Path, pairs: &[(String, Law)]) -> String {
    let stem = stem_of(file);
    let mut body = format!(
        "// Generated by `konpu scaffold` from `{}`.\n// Fill the bodies to encode each law, then run `./gradlew test`.\nimport kotlin.test.Test\n\nclass {stem}LawTests {{\n",
        file.display()
    );
    for (ty, law) in pairs {
        let kind = law_kind_str(law);
        let fn_name = format!("test_{ty}_{kind}");
        body.push_str(&format!(
            "    // konpu: law({kind})\n    @Test fun {fn_name}() {{ TODO(\"konpu scaffold: encode {kind} for {ty}\") }}\n\n"
        ));
    }
    body.push_str("}\n");
    body
}

fn render_ts(file: &Path, pairs: &[(String, Law)]) -> String {
    let mut body = format!(
        "// Generated by `konpu scaffold` from `{}`.\n// Fill the bodies to encode each law, then run your test runner (jest/vitest).\n\n",
        file.display()
    );
    for (ty, law) in pairs {
        let kind = law_kind_str(law);
        let fn_name = format!("test_{ty}_{kind}");
        body.push_str(&format!(
            "// konpu: law({kind})\ntest(\"{fn_name}\", () => {{ /* TODO: konpu scaffold — encode {kind} for {ty} */ }});\n\n"
        ));
    }
    body
}

fn law_kind_str(law: &Law) -> &'static str {
    match law {
        Law::Associativity => "associativity",
        Law::LeftIdentity => "left_identity",
        Law::RightIdentity => "right_identity",
        Law::InverseLeft => "inverse_left",
        Law::InverseRight => "inverse_right",
        Law::FunctorIdentity => "functor_identity",
        Law::FunctorComposition => "functor_composition",
        Law::ApplicativeIdentity => "applicative_identity",
        Law::ApplicativeComposition => "applicative_composition",
        Law::MonadLeftIdentity => "monad_left_identity",
        Law::MonadRightIdentity => "monad_right_identity",
        Law::MonadAssociativity => "monad_associativity",
    }
}

fn stem_of(input: &Path) -> &str {
    input.file_stem().and_then(|s| s.to_str()).unwrap_or("konpu")
}

fn out_path(input: &Path, suffix: &str) -> PathBuf {
    let stem = stem_of(input);
    let parent = input.parent().unwrap_or_else(|| Path::new("."));
    parent.join(format!("{stem}{suffix}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn law_kind_str_maps_associativity() {
        assert_eq!(law_kind_str(&Law::Associativity), "associativity");
    }

    #[test]
    fn out_path_rust_and_swift() {
        assert_eq!(
            out_path(Path::new("src/money.rs"), "_law_tests.rs"),
            Path::new("src/money_law_tests.rs")
        );
        assert_eq!(
            out_path(Path::new("Sources/Money.swift"), "LawTests.swift"),
            Path::new("Sources/MoneyLawTests.swift")
        );
    }

    #[test]
    fn render_swift_emits_xctest_with_law_comment() {
        let out = render_swift(
            Path::new("Money.swift"),
            &[("Money".to_string(), Law::Associativity)],
        );
        assert!(out.contains("import XCTest"));
        assert!(out.contains("final class MoneyLawTests: XCTestCase"));
        assert!(out.contains("// konpu: law(associativity)"));
        assert!(out.contains("func test_Money_associativity()"));
    }

    #[test]
    fn render_rust_emits_law_annotation() {
        let out = render_rust(
            Path::new("money.rs"),
            &[("Money".to_string(), Law::LeftIdentity)],
        );
        assert!(out.contains("#[konpu::law(left_identity)]"));
        assert!(out.contains("fn test_Money_left_identity()"));
    }
}
