//! `konpu scaffold` — 法則テストのスケルトン生成。
//!
//! 指定パスに存在するアノテーション付き宣言を走査し、各宣言について
//! `required_laws_for(structure)` を呼び、law ごとにスケルトン fn を
//! 出力したファイル `<stem>_law_tests.rs` を生成する。
//!
//! 出力形式（最小）:
//! ```text
//! #[test]
//! fn test_associativity() { unimplemented!() }
//! ```
//! law ごとに 1 関数。型名は fn 名に含めるため衝突しない。

use std::path::{Path, PathBuf};

use crate::analyze::check::required_laws_for;
use crate::analyze::parser;
use crate::analyze::template::ResolvedConfig;

#[derive(Debug, Clone)]
pub struct ScaffoldedFile {
    pub path: PathBuf,
    pub contents: String,
    pub decl_count: usize,
    pub test_count: usize,
}

/// `analyze_with_config` と同じ初期化で型付き decl を取得し、
/// パスごとに 1 つの scaffolded file を返す。
pub fn scaffold_path(path: &Path, _config: &ResolvedConfig) -> Vec<ScaffoldedFile> {
    let files = parser::collect_rust_files(path);
    let mut out = Vec::new();
    for file in files {
        if let Some(s) = scaffold_one(&file) {
            out.push(s);
        }
    }
    out
}

fn scaffold_one(file: &Path) -> Option<ScaffoldedFile> {
    let (_, tree) = parser::parse_file(file)?;
    let source = std::fs::read_to_string(file).ok()?;
    let root = tree.root_node();
    let decls = crate::analyze::extract::extract_declarations(root, &source, file);
    if decls.is_empty() {
        return None;
    }
    let mut tests: Vec<String> = Vec::new();
    let mut decl_count = 0usize;
    for decl in &decls {
        decl_count += 1;
        let laws = required_laws_for(&decl.target_structure);
        for law in &laws {
            let fn_name = fn_name_for(&decl.type_name, law);
            tests.push(format!(
                "#[test]\nfn {fn_name}() {{ unimplemented!(\"konpu scaffold: {fn_name}\") }}"
            ));
        }
    }
    if tests.is_empty() {
        return None;
    }
    let test_count = tests.len();
    let mut body = String::new();
    body.push_str(&format!(
        "//! Generated by `konpu scaffold` from `{}`.\n",
        file.display()
    ));
    body.push_str("//! Edit the unimplemented! bodies to encode the laws.\n\n");
    for t in &tests {
        body.push_str(t);
        body.push('\n');
    }
    let out_path = derive_out_path(file);
    Some(ScaffoldedFile {
        path: out_path,
        contents: body,
        decl_count,
        test_count,
    })
}

fn fn_name_for(type_name: &str, law: &crate::domain::konpu::Law) -> String {
    use crate::domain::konpu::Law;
    let kind = match law {
        Law::Associativity => "associativity",
        Law::LeftIdentity => "left_identity",
        Law::RightIdentity => "right_identity",
        Law::InverseLeft => "inverse_left",
        Law::InverseRight => "inverse_right",
        Law::FunctorIdentity => "functor_identity",
        Law::FunctorComposition => "functor_composition",
        Law::ApplicativeIdentity => "applicative_identity",
        Law::ApplicativeComposition => "applicative_composition",
        Law::MonadLeftIdentity => "monad_left_identity",
        Law::MonadRightIdentity => "monad_right_identity",
        Law::MonadAssociativity => "monad_associativity",
    };
    format!("test_{type_name}_{kind}")
}

fn derive_out_path(input: &Path) -> PathBuf {
    let stem = input
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("konpu");
    let parent = input.parent().unwrap_or_else(|| Path::new("."));
    parent.join(format!("{stem}_law_tests.rs"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::konpu::Law;

    #[test]
    fn fn_name_includes_type_and_law() {
        let n = fn_name_for("Foo", &Law::Associativity);
        assert_eq!(n, "test_Foo_associativity");
    }

    #[test]
    fn derive_out_path_keeps_parent() {
        let p = Path::new("src/domain/konpu/monoid.rs");
        let out = derive_out_path(p);
        assert_eq!(out, Path::new("src/domain/konpu/monoid_law_tests.rs"));
    }
}